#! /bin/bash -xe

# Wait for all interfaces to get added.
while [ -z $(ls /sys/class/net | grep cm) ]; do
    echo "CM interface not found"
    sleep 2
done
while [ -z $(ls /sys/class/net | grep eth1) ]; do
    echo "WAN interface not found"
    sleep 2
done
while [ -z $(ls /sys/class/net | grep aux0) ]; do
    echo "WAN interface not found"
    sleep 2
done

sysctl -p /etc/sysctl.conf

echo "Starting daemons."
for svc in zebra bgpd isisd ospfd ospf6d ripd ripngd pimd; do
 if [ -f /etc/quagga/${svc}.conf ]; then
  echo "Starting ${svc}."
  $svc -d
 fi
done

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
dhcrelay -4 -iu eth1 -id cm 172.25.1.20 || true
dhcrelay -6 -l cm -u 2001:dead:beef:2::20%eth1 || true

if [[ $# -gt 0 ]]; then
    exec "$@"
else
    # Keep the console alive.
    while :; do
        echo "------------------------------------------------------"
        echo "Attaching console. To disconnect, press Ctrl-P Ctrl-Q."
        echo "------------------------------------------------------"
        vtysh || :
        sleep 1
    done
fi
