#!/usr/bin/env python

# Copyright (c) 2015
#
# All rights reserved.
#
# This file is distributed under the Clear BSD license.
# The full text can be found in LICENSE in the root directory.
"""Configuration of dut, database, files and connect the devise to run."""
import atexit
import inspect
import json
import logging
import os
import queue
import re
import sys
import time
import traceback
from datetime import datetime

import matplotlib
import psutil
from apscheduler.schedulers.background import BackgroundScheduler
from termcolor import colored

import boardfarm.exceptions
import boardfarm.logging_config  # noqa  F401
from boardfarm import devices, library, tests
from boardfarm.dbclients import logstash, mongodblogger
from boardfarm.dbclients.lockableresources import LockableResources
from boardfarm.exceptions import BftNotSupportedDevice
from boardfarm.lib.bft_logging import create_file_logs, write_test_log
from boardfarm.lib.common import check_url, send_to_elasticsearch
from boardfarm.lib.DeviceManager import clean_device_manager, device_manager
from boardfarm.lib.env_helper import EnvHelper

logger = logging.getLogger("bft")

# Try to catch common mistakes: not installing boardfarm, or
# having wrong version installed.
try:
    import boardfarm
except Exception as e:
    logger.debug(e)
    logger.debug("Please install boardfarm with the command:")
    cmd = "pip install -e ."
    if not os.path.isfile("setup.py"):
        tmp = os.path.abspath(
            os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir)
        )
        cmd = f"cd {tmp} ; {cmd}"
    logger.debug(cmd)
    sys.exit(1)

# This is to parse tests early, and find issues here vs. after we connect to a board
tests.init()

matplotlib.use("Agg")


class FailedDevice:
    """failed device."""

    name = None


def bfcleanup():
    """bfcleanup: This method attempts to kill all the children processes under bft.

    Reason: some processes like Xvnc, firefox, are spawned by libraries using
    wrappers like EasyPorcess. Under certain circumstances these processes are
    not properly cleaned up, and are left hanging under the init process.
    """
    pid = os.getpid()
    for child in psutil.Process(pid).children(recursive=True):
        try:
            logger.debug(f"Killing process '{child.name()}'")
            child.kill()
        except Exception as e:
            logger.error(f"Failed to kill '{child.name()}':  {e}")


def threaded_device_helper(device, device_mgr, ret):
    """threaded_device_helper: Sets up dynamic devices from devices.

    :param device: object
    :param device_mgr: string
    :param ret: queue
    :return: true
    """
    from boardfarm.devices import get_device

    s = time.time()
    if "BFT_DEBUG" in os.environ:
        logger.debug(f"Connected to {device['name']}")

    try:
        dyn_dev = get_device(device["type"], **device, device_mgr=device_mgr)
    except BftNotSupportedDevice:
        logger.info(
            "Device %s not supported in this bft release + overlays, skipping..."
            % device["name"]
        )
        return
    except Exception:
        traceback.print_exc()
        failed = FailedDevice()
        if "name" not in device:
            logger.warning("Device in JSON does not have name, please fix!")
            failed.name = "Undefined"
            ret.put(failed)
            return
        failed.name = device["name"]
        ret.put(failed)
        return

    if "BFT_DEBUG" in os.environ:
        logger.debug(f"Time to instantiate device {device['name']} = {time.time() - s}")

    dyn_dev.name = device["name"]
    ret.put(dyn_dev)


def setup_dynamic_devices(config, device_mgr, env_helper):
    """Set up dynamic devices from devices node in JSON config file."""
    config.devices = []
    dynamic_devices = []  # pylint: disable=maybe-no-member
    ret = queue.Queue()

    for device in config.board["devices"]:
        threaded_device_helper(device, device_mgr, ret)

    for device in list(ret.queue):
        if type(device) is FailedDevice:
            raise Exception(f"Failed to instantiate device {device.name}")

        if not hasattr(device, "name") and " " not in device.name:
            raise Exception("Device does not have a proper name, please add!")

        if device.name in config.devices:
            logger.debug(f"Skipping duplicate device type: {device.name}")
            device.close()
            continue

        # Make it easy for devices to access other devices by giving it
        # a reference to the device manager
        device.dev = device_mgr
        device.env_helper = env_helper

        def create_device_helper(name, dev):
            setattr(config, name, dev)
            config.devices.append(name)

            # if this device is a wan cmts provisioner, we set the device name
            # TODO: this should be generic
            if getattr(dev, "wan_cmts_provisioner", False):
                config.provisioner = dev
                config.devices.append("provisioner")

        for dev in getattr(device, "extra_devices", []):
            if hasattr(dev, "name"):
                create_device_helper(dev.name, dev)
                dynamic_devices.append(dev.target)
            else:
                raise Exception("Extra device in config is not named! This is required")

        if not hasattr(device, "name"):
            raise Exception("Device in config is not named! This is required")
        create_device_helper(device.name, device)

        continue

    config.board["devices"].extend(dynamic_devices)


def connect_to_board(config, rootfs, kernel, device_mgr):
    tftp_server = None
    tftp_port = "22"

    # Connect to board
    board = devices.board_decider(
        config["board_type"],
        conn_cmd=config["conn_cmd"],
        power_ip=config.get("powerip", None),
        power_outlet=config.get("powerport", None),
        web_proxy=config.get("lan_device", None),
        tftp_server=config.get("wan_device", tftp_server),
        tftp_username=config.get("wan_username", "root"),
        tftp_password=config.get("wan_password", "bigfoot1"),
        tftp_port=config.get("wan_port", tftp_port),
        connection_type=config.get("connection_type", None),
        ssh_password=config.get("ssh_password", None),
        power_username=config.get("power_username", None),
        power_password=config.get("power_password", None),
        rootfs=rootfs,
        kernel=kernel,
        config=config,
        device_mgr=device_mgr,
    )
    return board


def connect_and_run(config):
    """Connect to device and run the configurations."""
    config, device_mgr, env_helper, _ = connect_to_devices(config)
    return run_tests(config, device_mgr, env_helper)


def connect_to_devices(config):
    """Connect to devices."""
    if config.test_args_location is not None:
        try:
            with open(config.test_args_location) as fp:
                config.test_args = json.load(fp)
        except Exception as e:
            logger.error(e)
            logger.error(
                colored(
                    f"ERROR: unable to fetch test args from {repr(config.test_args_location)}",
                    color="red",
                    attrs=["bold"],
                )
            )
            sys.exit(1)

    boardfarm.current_config = config

    # Find & import all available device classes
    devices.probe_devices()

    os.environ["TERM"] = "dumb"

    # Create output directory
    try:
        if not os.path.exists(config.output_dir):
            os.mkdir(config.output_dir)
    except Exception as error:
        logger.error(error)

    lockable_resouces = None
    if not config.bf_skip_reservation_check:
        jenkins_url = os.environ.get("JENKINS_URL", None)
        jenkins_token = os.environ.get("JENKINS_TOKEN", None)
        if jenkins_url is None or jenkins_token is None:
            raise OSError(
                "Missing Jenkins environment configuration."
                "Set JENKINS_URL and JENKINS_TOKEN environment variables."
            )
        ldap_credentials = os.environ.get("LDAP_CREDENTIALS", None)
        if ldap_credentials is None:
            raise OSError("Missing LDAP_CREDENTIALS environment config")
        ldap_username, _ = ldap_credentials.split(";")
        lockable_resouces = LockableResources(jenkins_url, ldap_username, jenkins_token)

    connected_to_board = False

    def update_value(regex, v):
        action, match, replace, _ = regex.split("/")
        assert action == "s"
        ret = re.sub(match, replace, v)

        if ret is not None:
            return ret
        else:
            return v

    def parse_type(regex, i):
        if type(i) == list:
            walk_list(regex, i)
            return True
        if type(i) == dict:
            walk_dict(regex, i)
            return True
        if type(i) == bool:
            return True
        if type(i) == int:
            return True

        return False

    def walk_list(regex, list_data):
        for i, v in enumerate(list_data):
            if parse_type(regex, v):
                continue
            list_data[i] = update_value(regex, v)

    def walk_dict(regex, d):
        for k, v in d.items():
            if parse_type(regex, v):
                continue
            d[k] = update_value(regex, v)

    for regex in config.regex_config:
        logger.debug(f"WARN: running regex replacement = {regex}")
        walk_dict(regex, config.boardfarm_config)

    board = None
    deny_list = []
    resource_name = None
    atexit.register(bfcleanup)
    while True:
        # DeviceManager makes it easy to find devices by name, type, features.
        clean_device_manager()
        device_mgr = devices.manager = device_manager()
        if lockable_resouces is not None:
            jenkins_job = os.environ.get("JOB_NAME", None)
            build_number = os.environ.get("BUILD_NUMBER", None)
            name, resource_name = lockable_resouces.acquire(
                config.bf_board_name, jenkins_job, build_number, config.bf_board_type
            )
        else:
            name = config.bf_board_name

        logger.info(
            colored(
                f"Checked out board named = {name}, type = {config.bf_board_type}",
                color="green",
                attrs=["bold"],
            )
        )

        try:
            # Use helper class to control access to configuration from tests
            config.board = boardfarm.lib.ConfigHelper().update(
                config.boardfarm_config[name]
            )
            if hasattr(config, "get_err_injection_dict"):
                config.board.update(
                    {"err_injection_dict": config.get_err_injection_dict()}
                )
        except Exception as e:
            logger.debug(e)
            logger.debug(
                f"Error reading info about board {name} from board farm configuration."
            )
            break

        try:
            # Store name of station and resource name in config for convenience
            config.board["station"] = name
            if resource_name is not None:
                config.board["resource_name"] = resource_name

            connected_to_board = True
            # None is legacy for tftp_server from before dynamic devices, leave it for now...
            reason = None
            board = connect_to_board(
                config.board, config.ROOTFS, config.KERNEL, device_mgr
            )

            deny_conn_to_dict = config.board.get("deny_conn_to", {})
            if deny_conn_to_dict and deny_conn_to_dict.get("devices", []):
                deny_list_names = deny_conn_to_dict["devices"]
                deny_list_options = deny_conn_to_dict.get("options", [])
                scheduler = BackgroundScheduler()
                for idx, board_name in enumerate(deny_list_names):
                    # get the deny board details
                    logger.debug(f"Denying access to board = {board_name}")

                    board_config = config.boardfarm_config[board_name]
                    aux_board = connect_to_board(board_config, None, None, None)

                    # This will be done in booting, once env schema is updated.
                    aux_board.hw.power.turn_off()

                    deny_list.append(aux_board)
                    setattr(device_mgr, f"__board{idx+2}", aux_board)

                    if "keep_alive" in deny_list_options:
                        if hasattr(aux_board, "setecho"):
                            aux_board.setecho(False)
                        scheduler.add_job(aux_board.touch, "interval", seconds=60)

                    logger.info(
                        colored(
                            f"Locked access to board = {board_name}",
                            color="yellow",
                            attrs=["bold"],
                        )
                    )
                if scheduler.get_jobs():
                    scheduler.start()

            # Make it easy for the board to access other devices by giving it
            # a reference to the device manager
            if hasattr(board, "set_device_mgr"):
                board.set_device_mgr(device_mgr)
            else:
                board.dev = device_mgr

            logger.info(f"dut device console = {colored('black', 'grey')}")

            # TODO: we should generically check these at one time in the future
            for x in ["UBOOT", "KERNEL", "ROOTFS", "META_BUILD"]:
                v = getattr(config, x, "")
                if v is not None and "mirror://" in v:
                    logger.debug(config.board)
                    r = getattr(config, x).replace("mirror://", config.board["mirror"])
                    if not check_url(r):
                        raise Exception(
                            "Unable to reach board mirror, trying next board"
                        )
                    setattr(config, x, r)

            if hasattr(board, "env_helper_type"):
                env_helper = board.env_helper_type(
                    config.test_args, mirror=config.board.get("mirror", None)
                )
            else:
                env_helper = EnvHelper(
                    config.test_args, mirror=config.board.get("mirror", None)
                )

            board.env_helper = env_helper

            if "devices" in config.board:
                setup_dynamic_devices(config, device_mgr, env_helper)

            def get_tftp_config(dev, board):
                saved = dev.logfile_read
                dev.logfile_read = None
                if hasattr(dev, "gw"):
                    board.tftp_server = dev.gw
                elif "wan-no-eth0" in dev.kwargs.get("options", ""):
                    board.tftp_server = dev.get_interface_ipaddr("eth1")
                else:
                    board.tftp_server = dev.get_interface_ipaddr("eth0")
                dev.logfile_read = saved
                board.tftp_username = "root"
                board.tftp_password = "bigfoot1"
                board.tftp_port = "22"
                board.tftp_dev = dev

            # check devices after they start for tftpd-server option if
            # if we still have not configured a tftp server
            for x in config.board["devices"]:
                if "tftpd-server" in x.get("options", ""):
                    get_tftp_config(getattr(config, x["name"]), board)
                    # TODO: how do we handle multiple tftp servers, break for now
                    break

        except boardfarm.exceptions.ConnectionRefused:
            connected_to_board = False
            reason = "ConnectionRefused"
        except KeyboardInterrupt:
            logger.warning("Keyboard interrupt")
            connected_to_board = False
            reason = "KeyboardInterrupt"
            sys.exit(2)
        except boardfarm.exceptions.BftSysExit as e:
            logger.error(f"BftSysExit: {str(e)}")
            sys.exit(3)
        except Exception as e:
            logger.debug(e)
            traceback.print_exc(file=sys.stdout)
            connected_to_board = False
            reason = str(e)
            message = f"last connected: {reason}"
            if lockable_resouces is not None:
                lockable_resouces.update_message(resource_name, message)
        finally:
            if not connected_to_board:
                logger.warning(
                    colored(
                        f"Failed to connect to a board or device on {name}: {reason}",
                        color="red",
                        attrs=["bold"],
                    )
                )
                if board:
                    board.close()
                if deny_list:
                    if scheduler.get_jobs():
                        scheduler.shutdown()
                    for dev in deny_list:
                        if dev:
                            dev.close()
        break

    if not connected_to_board:
        logger.warning(
            colored("Failed to connect to a board", attrs=["bold"], color="red")
        )
        sys.exit(2)

    try:
        logger.info(f"Using Board {name}, User {os.environ['BUILD_USER_ID']}")
    except Exception as e:
        logger.debug(e)
        logger.info(f"Using Board {name}, User {os.environ['USER']}")

    # Update config from board info
    if hasattr(board, "update_config"):
        board.update_config()

    logger.info("\n==========")
    library.printd(config.board)
    return config, device_mgr, env_helper, lockable_resouces


def run_tests(config, device_mgr, env_helper):
    """On the given devices, setup the environment and run tests."""
    os.environ["TEST_START_TIME"] = datetime.now().strftime("%s")
    tests_to_run = []
    # Add tests from specified suite
    logger.info(
        '==========\nTest suite "%s" has been specified, will attempt to run tests:'
        % config.TEST_SUITE
    )

    tests.init(config)
    from boardfarm import testsuites

    if config.TEST_SUITE not in testsuites.list_tests:
        logger.warning(f"Unable to find testsuite {config.TEST_SUITE}, aborting...")
        sys.exit(1)
    for i, name in enumerate(testsuites.list_tests[config.TEST_SUITE]):
        if isinstance(name, str):
            if name not in tests.available_tests:
                # we can either fail or ignore a missing test
                if config.TEST_SUITE_NOSTRICT:
                    logger.warning(f"\tWARNING: Test {name} NOT FOUND")
                    # add a place holder that will show up as skipped in the results
                    name = "selftest_fake_test"  # there must be a better way of getting the name!
                else:
                    # strict behaviour
                    logger.warning(
                        "Unable to load %s test from tests class!!!! Parsing of test via testsuite failed"
                        % name
                    )
                    sys.exit(1)
            test = tests.available_tests[name]
        else:
            test = name
        logger.info(f"  {i + 1} {test.__name__} from {inspect.getfile(test)}")
        # Create an instance of this test and give it a config and device manager.
        tests_to_run.append(test(config, device_mgr, env_helper))
    if hasattr(config, "EXTRA_TESTS") and config.EXTRA_TESTS:
        if tests_to_run[-1].__class__.__name__ == "Interact":
            logger.info("Last test is interact in testsuite, removing")
            tests_to_run.pop()

        logger.info("Extra tests specified on command line:")
        try:
            for name in config.EXTRA_TESTS:
                try:
                    t = tests.available_tests[name]
                except Exception as error:
                    logger.error(error)
                    raise Exception(
                        "Unable to load %s test from tests class!!!! Parsing of test selected via -e failed"
                        % name
                    )
                logger.info(f"  {t}")
                test = t(config, device_mgr, env_helper)
                tests_to_run.append(test)
        except Exception as e:
            logger.warning(e)
            logger.warning("Unable to find specified extra tests, aborting...")
            sys.exit(1)

    logger.info("==========")
    curr_test = None
    try:
        tests_pass = tests_fail = tests_skip = 0
        stop_testing = False
        curr_test = None
        for _, test in enumerate(tests_to_run):
            curr_test = test
            try:
                test.run()
            except boardfarm.exceptions.BootFail:
                stop_testing = True
            except Exception:
                # Keep going on to other tests
                pass
            finally:
                # Write test result messages to a file after each test
                os.environ["TEST_END_TIME"] = datetime.now().strftime("%s")
                full_results = library.process_test_results(
                    tests_to_run, config.golden_master_results
                )
                library.create_results_html(full_results, config, logger)
                json.dump(
                    full_results,
                    open(os.path.join(config.output_dir + "test_results.json"), "w"),
                    indent=4,
                    sort_keys=True,
                )

            curr_test = None
            grade = getattr(test, "result_grade", None)
            if grade == "OK" or grade == "Unexp OK":
                tests_pass += 1
            elif grade in ["FAIL", "Exp FAIL", "TD FAIL"]:
                tests_fail += 1
                # On failure, see status of devices
            elif grade in ["SKIP", "CC FAIL"] or grade is None:
                tests_skip += 1

            if stop_testing:
                break

    except KeyboardInterrupt:
        logger.info("Run interrupted. Wrapping up...")
        if curr_test is not None:
            curr_test.recover()

    logger.info(
        "Results run=%d failures=%d skipped=%d" % (tests_pass, tests_fail, tests_skip)
    )

    library.printd(config.board)
    with open("results/station_name.txt", "w") as f:
        print(config.board.get_station(), file=f)

    os.environ["TEST_END_TIME"] = datetime.now().strftime("%s")
    create_file_logs(config, device_mgr.board, tests_to_run, logger)

    # Close connections to all devices
    device_mgr.close_all()

    # Write test result messages to a file
    full_results = library.process_test_results(
        tests_to_run, config.golden_master_results
    )
    with open(os.path.join(config.output_dir + "test_results.json"), "w") as fout:
        json.dump(full_results, fout, indent=4, sort_keys=True)

    # run all analysis classes (post processing)
    # also, never fail so we don't block automation
    try:
        fname = "console-combined.log"
        with open(os.path.join(config.output_dir, fname)) as f:
            clog = f.read()
        if not clog:
            logger.debug(f"Skipping analysis because {fname} is empty...")
        else:
            from boardfarm import analysis

            for name in sorted(analysis.classes):
                analysis.classes[name]().analyze(clog, config.output_dir)
    except Exception as e:
        if not issubclass(type(e), (StopIteration)):
            logger.debug("Failed to run anaylsis:")
            logger.debug(e)

    # run exit funcs
    atexit._run_exitfuncs()

    # Create Pretty HTML output
    library.create_results_html(full_results, config, logger)

    for t in tests_to_run:
        write_test_log(t, config.output_dir)

    return library.create_info_for_remote_log(
        config, full_results, tests_to_run, logger, env_helper
    )


def main():
    """Collect arguments from the command-line and run with those."""
    # Read command-line arguments
    from boardfarm import arguments

    config = arguments.parse()

    # Run Tests
    info_for_remote_log = connect_and_run(config)

    # Save Results to file
    with open(
        os.path.join(config.output_dir + "info_for_remote_log.json"), "w"
    ) as fout:
        json.dump(info_for_remote_log, fout, indent=4, sort_keys=True)

    # Send Results to logstash, if configured
    try:
        if config.logging_server is not None:
            logstash.RemoteLogger(config.logging_server).log(info_for_remote_log)
    except Exception as e:
        logger.warning(e)
        logger.warning(
            "Unable to access logging_server specified in config. "
            "Results stored only locally."
        )

    # Send Results to ElasticSearch, if configured
    send_to_elasticsearch(config.elasticsearch_server, info_for_remote_log)

    # Send Results to MongoDB, if configured
    try:
        if hasattr(config, "mongodb") and config.mongodb["host"] is not None:
            mongodblogger.MongodbLogger(**config.mongodb).log(info_for_remote_log)
        else:
            logger.debug(
                "Needed mongodb parameters are not set, see config. Results stored locally."
            )
    except Exception as e:
        logger.warning(e)
        logger.warning(
            "Unable to store results to mongodb specified in config. "
            "Results stored locally."
        )


if __name__ == "__main__":
    main()
