#! /bin/bash -xe

# Wait for all interfaces to get added.
# By default only check for WAN and AUX interfaces
# Any other interface needs to be passed via command line to be checked.
if [[ $# -ne 0 ]]
then
    for i in $@;
    do
        while [ -z $(ls /sys/class/net | grep $i) ]
        do
            echo "$i interface not found"
            sleep 2
        done
    done
fi
while [ -z $(ls /sys/class/net | grep eth1) ]; do
    echo "WAN interface not found"
    sleep 2
done
while [ -z $(ls /sys/class/net | grep aux0) ]; do
    echo "WAN interface not found"
    sleep 2
done

sysctl -p /etc/sysctl.conf


echo "Starting daemons."
for svc in zebra bgpd isisd ospfd ospf6d ripd ripngd pimd; do
 if [ -f /etc/quagga/${svc}.conf ]; then
  echo "Starting ${svc}."
  cat >> /etc/monit/conf.d/quagga << EOF
  check process $svc with pidfile /var/run/quagga/$svc.pid
    start program = "/usr/sbin/$svc -d"
    stop program  = "/usr/sbin/service $svc stop"
EOF
 fi
done

# Add PIM6SD daemon
cp /usr/local/share/doc/pim6sd/pim6sd.conf.sample /etc/pim6sd.conf
cat >> /etc/monit/conf.d/pim6sd << EOF
  check process pim6sd with pidfile /var/run/pim6sd.pid
    start program = "/usr/local/sbin/pim6sd -f /etc/pim6sd.conf"
    stop program  = "kill -9 $(pgrep pim6sd)"
EOF

service monit start
service mrouted start

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

# Run sshd by default
/usr/sbin/sshd -D
